// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemporaryDataLayer;

namespace TemporaryDataLayer.Migrations
{
    [DbContext(typeof(TempShroomsDbContext))]
    [Migration("20220920051518_WallUpdate2")]
    partial class WallUpdate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id")
                        .HasName("PK_dbo.Roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PK_dbo.RoleClaims");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PK_dbo.UserClaims");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TemporaryDataLayer.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<string>("AbsentComment");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Bio");

                    b.Property<DateTime?>("BirthDay");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CultureCode");

                    b.Property<TimeSpan?>("DailyMailingHour");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime?>("EmploymentDate");

                    b.Property<string>("FacebookEmail");

                    b.Property<string>("FirstName");

                    b.Property<string>("GoogleEmail");

                    b.Property<bool>("IsAbsent");

                    b.Property<bool>("IsAnonymized");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsManagingDirector");

                    b.Property<bool>("IsOwner");

                    b.Property<bool>("IsTutorialComplete");

                    b.Property<int?>("JobPositionId");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("ManagerId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<int>("OrganizationId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PictureId");

                    b.Property<decimal>("RemainingKudos");

                    b.Property<int?>("RoomId");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("SittingPlacesChanged");

                    b.Property<decimal>("SpentKudos");

                    b.Property<string>("TimeZone");

                    b.Property<decimal>("TotalKudos");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime?>("VacationLastTimeUpdated");

                    b.Property<double?>("VacationTotalTime");

                    b.Property<double?>("VacationUnusedTime");

                    b.Property<double?>("VacationUsedTime");

                    b.Property<int?>("WorkingHoursId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.ApplicationUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("JobPositionId")
                        .HasName("IX_JobPositionId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("RoomId")
                        .HasName("IX_RoomId");

                    b.HasIndex("WorkingHoursId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TemporaryDataLayer.BlacklistUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .IsRequired();

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Reason");

                    b.Property<int>("Status");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PK_dbo.BlacklistUsers");

                    b.HasIndex("CreatedBy")
                        .HasName("IX_CreatedBy")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("ModifiedBy")
                        .HasName("IX_ModifiedBy")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("UserId")
                        .HasName("IX_UserId");

                    b.ToTable("BlacklistUsers");
                });

            modelBuilder.Entity("TemporaryDataLayer.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("BookCoverUrl");

                    b.Property<string>("Code")
                        .HasMaxLength(20);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<string>("Note")
                        .HasMaxLength(9000);

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Url")
                        .HasMaxLength(2000);

                    b.HasKey("Id")
                        .HasName("PK_dbo.Books");

                    b.HasIndex("ApplicationUserId")
                        .HasName("IX_ApplicationUserId");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Books");
                });

            modelBuilder.Entity("TemporaryDataLayer.BookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired();

                    b.Property<int>("BookOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<int>("OrganizationId");

                    b.Property<DateTime?>("Returned")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TakenFrom")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_dbo.BookLogs");

                    b.HasIndex("ApplicationUserId")
                        .HasName("IX_ApplicationUserId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("BookOfficeId")
                        .HasName("IX_BookOfficeId");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("BookLogs");
                });

            modelBuilder.Entity("TemporaryDataLayer.BookOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50);

                    b.Property<int>("OfficeId");

                    b.Property<int>("OrganizationId");

                    b.Property<int>("Quantity");

                    b.HasKey("Id")
                        .HasName("PK_dbo.BookOffices");

                    b.HasIndex("OfficeId")
                        .HasName("IX_OfficeId");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("BookId", "OfficeId")
                        .IsUnique()
                        .HasName("BookId_OfficeId");

                    b.ToTable("BookOffices");
                });

            modelBuilder.Entity("TemporaryDataLayer.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("AllowMaybeGoing")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowNotGoing")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("EventRecurring");

                    b.Property<int>("EventTypeId");

                    b.Property<int?>("EventTypeId1");

                    b.Property<string>("ImageName");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned");

                    b.Property<int>("MaxChoices")
                        .HasMaxLength(32767);

                    b.Property<int>("MaxParticipants")
                        .HasMaxLength(32767);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("OfficeId");

                    b.Property<string>("Offices")
                        .IsRequired();

                    b.Property<int?>("OrganizationId");

                    b.Property<string>("Place");

                    b.Property<DateTime>("RegistrationDeadline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2016, 5, 11, 11, 57, 2, 755, DateTimeKind.Local));

                    b.Property<string>("ResponsibleUserId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("WallId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Events");

                    b.HasIndex("EndDate")
                        .HasName("ix_end_date")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("EventTypeId")
                        .HasName("IX_EventTypeId");

                    b.HasIndex("EventTypeId1");

                    b.HasIndex("OfficeId")
                        .HasName("IX_OfficeId");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId");

                    b.HasIndex("ResponsibleUserId")
                        .HasName("IX_ResponsibleUserId");

                    b.HasIndex("StartDate")
                        .HasName("ix_start_date")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("WallId")
                        .HasName("IX_WallId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TemporaryDataLayer.EventOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<Guid?>("EventId1");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Option")
                        .IsRequired();

                    b.Property<int>("Rule")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK_dbo.EventOptions");

                    b.HasIndex("EventId")
                        .HasName("IX_EventId");

                    b.HasIndex("EventId1");

                    b.ToTable("EventOptions");
                });

            modelBuilder.Entity("TemporaryDataLayer.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("");

                    b.Property<string>("AttendComment");

                    b.Property<int>("AttendStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<Guid?>("EventId1");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.HasKey("Id")
                        .HasName("PK_dbo.EventParticipants");

                    b.HasIndex("ApplicationUserId")
                        .HasName("IX_ApplicationUserId");

                    b.HasIndex("EventId")
                        .HasName("IX_EventId");

                    b.HasIndex("EventId1");

                    b.HasIndex("IsDeleted")
                        .HasName("nci_wi_EventParticipants_CA1F6B4699FAB2347B166CEA9639C7E8")
                        .HasAnnotation("SqlServer:Clustered", false)
                        .HasAnnotation("SqlServer:Include", new[] { "EventId" });

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("TemporaryDataLayer.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsShownWithMainEvents")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSingleJoin");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("OrganizationId");

                    b.Property<bool>("SendEmailToManager")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("SendWeeklyReminders")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("SingleJoinGroupName")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("PK_dbo.EventTypes");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("TemporaryDataLayer.ExternalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrganizationId");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PK_dbo.ExternalLinks");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("ExternalLinks");
                });

            modelBuilder.Entity("TemporaryDataLayer.FilterPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("ForPage");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Preset")
                        .IsRequired();

                    b.HasKey("Id")
                        .HasName("PK_dbo.FilterPresets");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("FilterPresets");
                });

            modelBuilder.Entity("TemporaryDataLayer.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int?>("OfficeId");

                    b.Property<int>("OrganizationId");

                    b.Property<string>("PictureId");

                    b.Property<int?>("Picture_Id");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Floors");

                    b.HasIndex("OfficeId")
                        .HasName("IX_OfficeId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Picture_Id")
                        .HasName("IX_Picture_Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("TemporaryDataLayer.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Title");

                    b.HasKey("Id")
                        .HasName("PK_dbo.JobPositions");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("TemporaryDataLayer.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(5000);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EntryFee");

                    b.Property<int>("GiftedTicketLimit")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<bool>("IsRefundFailed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("OrganizationId");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Lotteries");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Lotteries");
                });

            modelBuilder.Entity("TemporaryDataLayer.LotteryParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime");

                    b.Property<int>("LotteryId");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("UserId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.LotteryParticipants");

                    b.HasIndex("LotteryId")
                        .HasName("IX_LotteryId");

                    b.HasIndex("UserId")
                        .HasName("IX_UserId");

                    b.ToTable("LotteryParticipants");
                });

            modelBuilder.Entity("TemporaryDataLayer.Models.Events.EventParticipantEventOption", b =>
                {
                    b.Property<int>("EventParticipantId")
                        .HasColumnName("EventParticipant_Id");

                    b.Property<int>("EventOptionId")
                        .HasColumnName("EventOption_Id");

                    b.HasKey("EventParticipantId", "EventOptionId")
                        .HasName("PK_dbo.EventParticipantEventOptions");

                    b.HasIndex("EventOptionId")
                        .HasName("IX_EventOption_Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("EventParticipantId")
                        .HasName("IX_EventParticipant_Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("EventParticipantEventOptions");
                });

            modelBuilder.Entity("TemporaryDataLayer.Models.ModuleOrganization", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnName("Module_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnName("Organization_Id");

                    b.HasKey("ModuleId", "OrganizationId")
                        .HasName("PK_dbo.ModuleOrganizations");

                    b.HasIndex("ModuleId")
                        .HasName("IX_Module_Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasName("IX_Organization_Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("ModuleOrganizations");
                });

            modelBuilder.Entity("TemporaryDataLayer.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Modules");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TemporaryDataLayer.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("OrganizationId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Offices");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("TemporaryDataLayer.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthenticationProviders");

                    b.Property<string>("BookAppAuthorizationGuid");

                    b.Property<string>("CalendarId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CultureCode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("en-US");

                    b.Property<bool>("HasRestrictedAccess")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("HostName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("KudosYearlyMultipliers");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<bool>("RequiresUserConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("TimeZone")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("FLE Standard Time");

                    b.Property<string>("WelcomeEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10000)
                        .HasDefaultValue("<p style=\"text - align:center; font - size:14px; font - weight:400; margin: 0 0 0 0; \">Administrator has confirmed your registration</p>");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Organizations");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TemporaryDataLayer.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("ParentPageId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Pages");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("ParentPageId")
                        .HasName("IX_ParentPageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("TemporaryDataLayer.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("Height");

                    b.Property<byte[]>("ImageData");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("MimeType");

                    b.Property<byte[]>("MiniThumbData");

                    b.Property<int?>("MiniThumbHeight");

                    b.Property<int?>("MiniThumbWidth");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("OrganizationId");

                    b.Property<byte[]>("ThumbData");

                    b.Property<int?>("ThumbHeight");

                    b.Property<int?>("ThumbWidth");

                    b.Property<int?>("Width");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Pictures");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("TemporaryDataLayer.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coordinates");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("FloorId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("RoomTypeId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Rooms");

                    b.HasIndex("FloorId")
                        .HasName("IX_FloorId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("RoomTypeId")
                        .HasName("IX_RoomTypeId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TemporaryDataLayer.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasMaxLength(7);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("CreatedBy");

                    b.Property<string>("IconId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWorkingRoom")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("OrganizationId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.RoomTypes");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("TemporaryDataLayer.SyncToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Token");

                    b.HasKey("Id")
                        .HasName("PK_dbo.SyncTokens");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("SyncTokens");
                });

            modelBuilder.Entity("TemporaryDataLayer.VacationPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("OrganizationId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.VacationPages");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("VacationPages");
                });

            modelBuilder.Entity("TemporaryDataLayer.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("OrganizationId");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Walls");

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("TemporaryDataLayer.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy");

                    b.Property<TimeSpan?>("EndTime");

                    b.Property<bool>("FullTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted");

                    b.Property<TimeSpan?>("LunchEnd");

                    b.Property<TimeSpan?>("LunchStart");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("OrganizationId");

                    b.Property<int?>("PartTimeHours");

                    b.Property<TimeSpan?>("StartTime");

                    b.HasKey("Id")
                        .HasName("PK_dbo.WorkingHours");

                    b.HasIndex("ApplicationUserId")
                        .HasName("IX_ApplicationUserId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("OrganizationId")
                        .HasName("IX_OrganizationId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.ApplicationUser", b =>
                {
                    b.HasOne("TemporaryDataLayer.JobPosition")
                        .WithMany("Users")
                        .HasForeignKey("JobPositionId")
                        .HasConstraintName("FK_dbo.ApplicationUser_dbo.JobPositions_JobPositionId");

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.ApplicationUser_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Room")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_dbo.ApplicationUser_dbo.Rooms_RoomId");

                    b.HasOne("TemporaryDataLayer.WorkingHours", "WorkingHours")
                        .WithMany()
                        .HasForeignKey("WorkingHoursId");
                });

            modelBuilder.Entity("TemporaryDataLayer.BlacklistUser", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_dbo.BlacklistUsers_dbo.AspNetUsers_CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_dbo.BlacklistUsers_dbo.AspNetUsers_ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.BlacklistUsers_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_dbo.BlacklistUsers_dbo.AspNetUsers_UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.Book", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .HasConstraintName("FK_dbo.Books_dbo.AspNetUsers_ApplicationUserId");

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Books_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.BookLog", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .HasConstraintName("FK_dbo.BookLogs_dbo.AspNetUsers_ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.BookOffice", "BookOffice")
                        .WithMany("BookLogs")
                        .HasForeignKey("BookOfficeId")
                        .HasConstraintName("FK_dbo.BookLogs_dbo.BookOffices_BookOfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.BookLogs_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.BookOffice", b =>
                {
                    b.HasOne("TemporaryDataLayer.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK_dbo.BookOffices_dbo.Books_BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.Office", "Office")
                        .WithMany("BookOffices")
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("FK_dbo.BookOffices_dbo.Offices_OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.BookOffices_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.Event", b =>
                {
                    b.HasOne("TemporaryDataLayer.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .HasConstraintName("FK_dbo.Events_dbo.EventTypes_EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId1");

                    b.HasOne("TemporaryDataLayer.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("FK_dbo.Events_dbo.Offices_OfficeId");

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Events_dbo.Organizations_OrganizationId");

                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .HasConstraintName("FK_dbo.Events_dbo.ApplicationUser_ResponsibleUserId");

                    b.HasOne("TemporaryDataLayer.Wall", "Wall")
                        .WithMany()
                        .HasForeignKey("WallId")
                        .HasConstraintName("FK_dbo.Events_dbo.Walls_WallId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.EventOption", b =>
                {
                    b.HasOne("TemporaryDataLayer.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_dbo.EventOptions_dbo.Events_EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Event")
                        .WithMany("EventOptions")
                        .HasForeignKey("EventId1");
                });

            modelBuilder.Entity("TemporaryDataLayer.EventParticipant", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .HasConstraintName("FK_dbo.EventParticipants_dbo.ApplicationUser_ApplicationUserId");

                    b.HasOne("TemporaryDataLayer.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_dbo.EventParticipants_dbo.Events_EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId1");
                });

            modelBuilder.Entity("TemporaryDataLayer.EventType", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.EventTypes_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.ExternalLink", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.ExternalLinks_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.FilterPreset", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.FilterPresets_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.Floor", b =>
                {
                    b.HasOne("TemporaryDataLayer.Office", "Office")
                        .WithMany("Floors")
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("FK_dbo.Floors_dbo.Offices_OfficeId");

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Floors_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("Picture_Id")
                        .HasConstraintName("FK_dbo.Floors_dbo.Pictures_Picture_Id");
                });

            modelBuilder.Entity("TemporaryDataLayer.JobPosition", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.JobPositions_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.Lottery", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Lotteries_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TemporaryDataLayer.ImageCollection", "Images", b1 =>
                        {
                            b1.Property<int>("LotteryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Serialized")
                                .HasColumnName("Images");

                            b1.HasKey("LotteryId");

                            b1.ToTable("Lotteries");

                            b1.HasOne("TemporaryDataLayer.Lottery")
                                .WithOne("Images")
                                .HasForeignKey("TemporaryDataLayer.ImageCollection", "LotteryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TemporaryDataLayer.LotteryParticipant", b =>
                {
                    b.HasOne("TemporaryDataLayer.Lottery", "Lottery")
                        .WithMany()
                        .HasForeignKey("LotteryId")
                        .HasConstraintName("FK_dbo.LotteryParticipants_dbo.Lotteries_LotteryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_dbo.LotteryParticipants_dbo.AspNetUsers_UserId");
                });

            modelBuilder.Entity("TemporaryDataLayer.Models.Events.EventParticipantEventOption", b =>
                {
                    b.HasOne("TemporaryDataLayer.EventOption", "EventOption")
                        .WithMany("EventParticipantEventOptions")
                        .HasForeignKey("EventOptionId")
                        .HasConstraintName("FK_dbo.EventParticipantEventOptions_dbo.EventOptions_EventOption_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.EventParticipant", "EventParticipant")
                        .WithMany("EventParticipantEventOptions")
                        .HasForeignKey("EventParticipantId")
                        .HasConstraintName("FK_dbo.EventParticipantEventOptions_dbo.EventParticipants_EventParticipant_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.Models.ModuleOrganization", b =>
                {
                    b.HasOne("TemporaryDataLayer.Module", "Module")
                        .WithMany("ShroomsModuleOrganizations")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("FK_dbo.ShroomsModuleOrganizations_dbo.ShroomsModules_ShroomsModule_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany("ShroomsModuleOrganizations")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.ShroomsModuleOrganizations_dbo.Organizations_Organization_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.Office", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Offices_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("TemporaryDataLayer.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Building");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("Street");

                            b1.HasKey("OfficeId");

                            b1.ToTable("Offices");

                            b1.HasOne("TemporaryDataLayer.Office")
                                .WithOne("Address")
                                .HasForeignKey("TemporaryDataLayer.Address", "OfficeId")
                                .HasConstraintName("FK_dbo.Offices_dbo.Address_AddressTempId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TemporaryDataLayer.Page", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Pages_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Page", "ParentPage")
                        .WithMany()
                        .HasForeignKey("ParentPageId")
                        .HasConstraintName("FK_dbo.Pages_dbo.Pages_ParentPageId");
                });

            modelBuilder.Entity("TemporaryDataLayer.Picture", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Pictures_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.Room", b =>
                {
                    b.HasOne("TemporaryDataLayer.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .HasConstraintName("FK_dbo.Rooms_dbo.Floors_FloorId");

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Rooms_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK_dbo.Rooms_dbo.RoomTypes_RoomTypeId");
                });

            modelBuilder.Entity("TemporaryDataLayer.RoomType", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.RoomTypes_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.SyncToken", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.SyncTokens_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.VacationPage", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.VacationPages_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemporaryDataLayer.Wall", b =>
                {
                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.Walls_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TemporaryDataLayer.WorkingHours", b =>
                {
                    b.HasOne("TemporaryDataLayer.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .HasConstraintName("FK_dbo.WorkingHours_dbo.AspNetUsers_ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TemporaryDataLayer.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("FK_dbo.WorkingHours_dbo.Organizations_OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
